name: Node CI

on:
  push:
    branches: 
      - src
    paths: 
      - 'docs/*'

jobs:
  build:

    runs-on: [ubuntu-18.04]

    steps:
    - uses: actions/checkout@v1
    - run: npm ci
    - run: npm run build
    - name: Move dist to master
      run: 
        git add -- docs/.vuepress/dist/* &&
        git stash push  &&
        git checkout master  &&
        git stash pop
    - name: Move dist to correct directory
      run: 
        Get-ChildItem -Path "docs/.vuepress/dist" -Recurse -File | ForEach-Object -Process { Move-Item $_  (".\\" + [regex]::Replace($_.FullName, ".*dist\\", "")) -Force };
        Remove-Item -Path "docs" -Recurse -Force;
      shell: pwsh
    - name: Push to master
      run:
        git add -- ./ &&
        git commit -m Updated &&
        git pull &&
        git push
